name: build_osx

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-13
 
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Install MacPorts (new step)
      - uses: melusina-org/setup-macports@v1

      # Install ccache using port (optional, adjust as needed)
      - name: Install ccache
        run: |
          sudo port install ccache
          sudo port install python311

      # Runs a set of commands using the runner's shell
      - name: Build-commands
        run: |
          echo Starting Build-commands
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          uname -a
          cd $GITHUB_WORKSPACE
          ls -lh
          cd src
          python3 build_linux.py
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: usearch12-osx-binary
          path: /Users/runner/work/usearch12/usearch12/bin/usearch12
      - name: Upload makefile.stderr artifact
        uses: actions/upload-artifact@v4
        with:
          name: makefile.stderr-osx
          path: /Users/runner/work/usearch12/usearch12/src/makefile.stderr
      - name: Upload makefile.stdout artifact
        uses: actions/upload-artifact@v4
        with:
          name: makefile.stdout-osx
          path: /Users/runner/work/usearch12/usearch12/src/makefile.stdout
