name: build_linux

on:
  workflow_dispatch:
jobs:
  build-aarch64:
    name: Linux aarch64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: uraimo/run-on-arch-action@v2
      with:
       arch: aarch64
       distro: ubuntu20.04
       githubToken: ${{ github.token }}
       dockerRunArgs: |
          --volume "${PWD}:/usearch12"
       install: |
          apt-get update -q -y
          apt-get install -q -y make g++ file git python3 ccache
       run: |
          git config --global --add safe.directory /usearch12
          cd /usearch12  
          uname -a
          lscpu
          cd src/
          python3 build_linux.py
          file /usearch12/bin/usearch12 | grep aarch64
          ls
          pwd
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: usearch12-linux-aarch64-binary
        path: /usearch12/bin/usearch12
    - name: Upload make.stderr artifact
      uses: actions/upload-artifact@v4
      with:
          name: make.stderr-linux-aarch64
          path: /usearch12/src/make.stderr
    - name: Upload make.stdout  artifact
      uses: actions/upload-artifact@v4
      with:
          name: make.stdout-linux-aarch64
          path: /usearch12/src/make.stdout
  build:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
           python-version: '3.10' 

      # Runs a set of commands using the runners shell
      - name: Build-commands
        run: |
          sudo apt-get install -q -y ccache
          echo Starting Build-commands
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          uname -a
          cd $GITHUB_WORKSPACE
          ls -lh
          cd src
          python3 build_linux.py
          file /home/runner/work/usearch12/usearch12/bin/usearch12 | grep x86-64
          ls
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: usearch12-linux-binary
          path: /home/runner/work/usearch12/usearch12/bin/usearch12
      - name: Upload make.stderr  artifact
        uses: actions/upload-artifact@v4
        with:
          name: make.stderr-linux
          path: /home/runner/work/usearch12/usearch12/src/make.stderr
      - name: Upload make.stdout  artifact
        uses: actions/upload-artifact@v4
        with:
          name: make.stdout-linux
          path: /home/runner/work/usearch12/usearch12/src/make.stdout
